version: 2

sources:
  - name: erp
    description: 'Essa é a fonte do sistema ERP da northwind com dados de vendas e transações.'
    database: fea24_6
    schema: raw_northwind
    tables:
      - name: employee
        description: 'Tabela com dados de funcionários.'
        columns:
          - name: id
            description: 'Chave primária da tabela funcionários.'
            tests:
              - unique
              - not_null